### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by lipnitsk** [oskarirauta/populatefs#5]
Hi, I'm assuming the license is GPL since the code is based on genext2fs, but could you please add a LICENSE file to remove this ambiguity?

Thanks!

**Comment by oskarirauta** [comment]
Based on genext2fs but mostly to provide similar functionality.
It is freeware, so it’s provided as-is for any use, modification, for any purpose, whether commercial or non-commercial.
It’s also available as adopt if one believes they need to improve it, I created it for one purpose:
I needed a versatile tool to build a filesystem image for rpi with openwrt builder. Also, I gave openwrt community a possibility
to use this, since with this, unlike with genext2fs - you can set filesystem flags allowing for example, resizing of ext fs. They were not interested and if I remember correctly, they no longer use genext2fs, nor this little utility.

But since there was some work involved in creating this, I decided to put it out in public available for all, so people wouldn’t need to re-invent the wheel.

You are free to use it as is, or to do anything with it. Even remove references to me, if you feel that it’s necessary, or you don’t want to give credits. If you feel that you should ask if I permit something with it, go ahead and ask - but mostly you don’t need to; answer is: go ahead, I am happy if someone finds use for something I created :)

**Comment by lipnitsk** [comment]
Ok, thanks! I will fork this repo and release version 1.0 from https://github.com/lipnitsk/populatefs

**Comment by oskarirauta** [comment]
No problem. Happy To assist ;)

Lähetetty iPhonesta
